import Head from 'next/head'
// import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>FAQ App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-roboto">
        <div className="text-2xl flex justify-center gap-5 max-w-s mx-auto mt-9">
          <Link href="/faq-carer">
            <a className="border block text-cyan-800 p-4 rounded-lg hover:text-black bg-cyan-50 border-cyan-50">
              carer's FAQ
            </a>
          </Link>
          <Link href="/faq-client">
            <a className="border block text-cyan-800 p-4 rounded-lg hover:text-black bg-cyan-50 border-cyan-50">
              client's FAQ
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
